spring:
  application:
    name: grocery-tracker

  datasource:
    url: jdbc:postgresql://postgres:5432/grocerydb
    username: grocery
    password: grocery_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true

  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}
    username: ""        # disabled security
    password: ""        # disabled security
    connection-timeout: 30s
    socket-timeout: 30000

logging:
  level:
    org.springframework.data.elasticsearch: INFO
